
title: Material Saber
email: rokhim.whd@gmail.com
description: >
  My Private blog for diary, notes, any more.
baseurl: ""
url: ""

markdown: kramdown

twitterUsername: rokhiminwahid
githubUsername: rokhimin

themeColor: default
fixedNav: 'true'

permalink: /:title.rb
markdown: kramdown
include: [_pages]
exclude: [_site, LICENSE, README.md]
sass:
  style: compressed
